apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smoke-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KonstantinFomenko/homelab-gitops.git
    targetRevision: main
    path: platform/smoke-test
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
